### ISSUE TITLE
How to use without stack?

### ISSUE THREAD

**Issue by vyorkin** [serokell/co-log-sys#1]
Thanks for your work on this package!

I've noticed that it depends on `loot-prelude` package (which is not on Hackage).
https://github.com/serokell/co-log-sys/blob/8a1910330ebc3937518ab0e8e3d3516600f38b41/stack.yaml#L17

I use `cabal new-` (nix-style local builds, without stack) and it can't resolve the `loot-prelude` dependency:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: trader-0.1.0.0 (user goal)
[__1] trying: co-log-sys-0.1.0.0 (dependency of trader)
[__2] unknown package: loot-prelude (dependency of co-log-sys)
[__2] fail (backjumping, conflict set: co-log-sys, loot-prelude)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: trader, co-log-sys, loot-prelude
```

**Comment by flyingleafe** [comment]
@vyorkin Thanks for your feedback. I think that we will remove `loot-prelude` dependency altogether and use only `universum` instead. It will be done shortly, you can expect an update tomorrow.

**Comment by flyingleafe** [comment]
@vyorkin
Version 0.1.1.0 without `loot-prelude` dependency and fully compatible with `cabal` is out: http://hackage.haskell.org/package/co-log-sys
